version: "3.8"
services:

  app:
    container_name: vue-app
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      # bind:local
      - "8000:8080"
    networks:
      serveriry:
        ipv4_address: 10.10.0.2
    depends_on:
      - directus

  db:
    container_name: postgresql
    image: postgres:15-alpine
    volumes:
      - directus_data_dev:/var/lib/postgresql/data
    networks:
      serveriry:
        ipv4_address: 10.10.0.3
    env_file:
      - ./.env.dev.db

  cache:
    container_name: cache
    image: redis:6
    networks:
      serveriry:
        ipv4_address: 10.10.0.4

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - "8001:8055"
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - directus_uploads_dev:/directus/uploads
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    networks:
      serveriry:
        ipv4_address: 10.10.0.5
    depends_on:
      - cache
      - db
    env_file:
      - ./.env.dev

volumes:
  directus_data_dev:
  directus_uploads_dev:

networks:
  serveriry:
    driver: bridge
    name: "www-serveri-ry-dev"
    ipam:
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1
